### ISSUE TITLE
Installed Apk not going further after first Activity

### ISSUE THREAD

**Issue by Anishnarang99** [rakshitsoni02/newsApp#2]
https://github.com/Anishnarang99/newsApp_clone1.git

**Comment by Khyati1992** [comment]
`http://216.158.225.126/~androidapp/index.php/api/`

 base URL is not working, please provide working URL.

**Comment by rakshitsoni02** [comment]
i would suggest you to use dummy JSON response for testing as per models. As API backend is no longer available

**Comment by Khyati1992** [comment]
could you please provide me your JSON structure to create dummy JSON response. or if you have any dummy JSON available. as you have used many of models.
